### PR TITLE
Ease shadow-box and border on TOC

### PR DESCRIPTION
**Pull request by hirako2000**
This change softens the shadow effect on the Table of Content element.

### CODE REVIEW

**Comment by hirako2000** [comment]
**Before**
image
**After**
image

**Comment by robinsloan** [comment]
Thanks for the pull request! Can you talk a little bit about your rationale for this change?

**Comment by hirako2000** [comment]
Attempt at a better elevation effect. Everything in design is somewhat subjective, my rational is the use of transparency, 0.15 is pretty standard to reduce the glowing effect, and the size reduction to get closer to the elevation effect I believe is intended there.

We can still do better.

https://uglyduck.ca/better-box-shadows/

I've merely attempted to quickly improve the one obvious thing that stand out in the styling. Again things are subjective, but I clicked on the TOC button and I thought this can't be right. Maybe I went too far and the effect is too subtle.

**Comment by robinsloan** [comment]
That's very useful---thanks! I'll confess that I had dialed the effect up to incandescence intentionally; however, I'm totally willing to take another look. I'll mull this over. Thanks for the thoughtful edit!

**Comment by hirako2000** [comment]
If that is how you want it, keep it that way of course.

Thanks for authoring this project, and for the chat.

**Pull request closed without merging**
